### PR TITLE
fix(app-switcher): scroll on expansion

### PR DESCRIPTION
**Pull request by christianmemije**
Scroll applications into view on expand

### CODE REVIEW

**Comment by aqupriyanka** [comment]
Sometimes its not working and sometimes its working on second click. Attached the gif for reference.
app_switcher_bug

**Comment by adamnel** [comment]
@christianmemije The entire dialog should just get longer if need be, not scroll. This could be used in the edge case where we run out of room if we have a very long list.

**Comment by christianmemije** [comment]
> @christianmemije The entire dialog should just get longer if need be, not scroll. This could be used in the edge case where we run out of room if we have a very long list.

This is for an edge-case. The menu does increase size. It's just that the max-height of `.td-menu-content` is set to `50vh` within Covalent.

**Comment by emoralesb05** [comment]
Isnt the height defined in `mat-menu`?

**Comment by christianmemije** [comment]
Defined within `td-menu`
https://github.com/Teradata/covalent/blob/develop/src/platform/core/menu/menu.component.scss#L41

**Comment by emoralesb05** [comment]
Oh, i thought it came from mat-menu.. if thats the case we need to remove that. And make it so that the height its decided on implementation.

**Comment by christianmemije** [comment]
> Oh, i thought it came from mat-menu.. if thats the case we need to remove that. And make it so that the height its decided on implementation.
> 
> Edit: Well, potentially would be to remove it. We just need to make sure we dont break usage since its technically a breaking change.

Opened  https://github.com/Teradata/covalent/issues/1765

**Pull request merged**
