### PR TITLE
feat(sqle): add credentials dialog

### PR DESCRIPTION
**Pull request by emoralesb05**
Add credentials dialog for reusability and standardization with lots of improvements.

### Animations

credentials-dialog-gif

### CODE REVIEW

**Comment by owilliams320** [comment]
anyway we can get a gif preview 😎

**Comment by emoralesb05** [comment]
Updated with gif~

**Comment by adamnel** [comment]
Are we manually enlarging that double-line dropdown menu? If so, we should make it a bit bigger to fit the extra content.

Instead of the radio buttons, let's use tabs to choose the second set of options:

image

**Comment by emoralesb05** [comment]
We are actually making it smaller so its the same size as the inputs which is the default size of an `outline` form field.

And using thabs seems semantically incorrect since its a form element.

**Comment by owilliams320** [comment]
LGTM

**Comment by adamnel** [comment]
@emoralesb05 

**Input box** 
Are you planning on removing one of the lines then? More content needs more space.

**Tabs** 
How so? This is the primary purpose of tabs. Radio buttons don't give the user any indication of what's going to happen. Could be a choice, could toggle some content ¯\_(ツ)_/¯. Tabs are built for this. How does their presence in a form change the math?

**Comment by emoralesb05** [comment]
Its a selection form, a tab is a display mechanism.

**Comment by emoralesb05** [comment]
A bit bigger now to fit the content

image

**Comment by adamnel** [comment]
So the argument is that choosing a tab doesn't imply making a choice? Whereas a radio button is more explicit?

**Comment by emoralesb05** [comment]
Correct, a tab is for showing/hiding content that the user will then select (without the tab being a part of the form data)

In this case, the radio selection is also part of the form data.

**Pull request merged**
